CREATE TABLE AERONAVES(
    ID_AERONAVE INT PRIMARY KEY,
    REF VARCHAR2(10) UNIQUE,
    TOTAL_DE_ASSENTOS INT,
    MODELO VARCHAR2(20),
    MARCA VARCHAR2(15)
);
CREATE SEQUENCE SEQ_AERONAVE START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRI_AERONAVE_ID


CREATE TABLE ASSENTOS(
    ID_ASSENTO INT PRIMARY KEY,
    ID_AERONAVE INT,
    REF VARCHAR2(5),
    STATUS VARCHAR2(15),
    FOREIGN KEY (ID_AERONAVE) REFERENCES AERONAVES(ID_AERONAVE)
);

CREATE TABLE AEROPORTOS(
    ID_AEROPORTO INT PRIMARY KEY,
    NOME_OFICIAL VARCHAR2(35),
    COD_IATA VARCHAR2(3),
    CIDADE VARCHAR2(20)
);

CREATE TABLE TRECHOS(
    ID_TRECHO INT PRIMARY KEY,
    ORIGEM INT,
    DESTINO INT,
    FOREIGN KEY (ORIGEM) REFERENCES AEROPORTOS(ID_AEROPORTO),
    FOREIGN KEY (DESTINO) REFERENCES AEROPORTOS(ID_AEROPORTO)
);

CREATE TABLE VOOS(
    ID_VOO INT PRIMARY KEY,
    TRECHO INT,
    DTH_PARTIDA_PREVISTA DATE,
    DTH_CHEGADA_PREVISTA DATE,
    AERONAVE INT,
    FOREIGN KEY (TRECHO) REFERENCES TRECHOS(ID_TRECHO),
    FOREIGN KEY (AERONAVE) REFERENCES AERONAVES(ID_AERONAVE)
);

CREATE TABLE MAPA_DE_ASSENTOS(
    ID_MAPA_ASSENTOS INT PRIMARY KEY,
    VOO INT,
    ASSENTO INT,
    ASSENTO_REF INT,
    STATUS INT,
    TICKET INT,
    FOREIGN KEY (VOO) REFERENCES VOOS(ID_VOO),
    FOREIGN KEY (ASSENTO) REFERENCES ASSENTOS(ID_ASSENTO),
    FOREIGN KEY (ASSENTO_REF) REFERENCES ASSENTOS(ID_ASSENTO),
    FOREIGN KEY (STATUS) REFERENCES ASSENTOS(ID_ASSENTO)
);